name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *" # every day at 02:30 UTC (08:00 IST)

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync accepted submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          verbose: true
          commit-header: "Sync LeetCode:"
